"""Initial revision

Revision ID: 27ce5f7bf5d5
Revises: 3747e8230aa4
Create Date: 2024-03-05 11:03:02.955504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ce5f7bf5d5'
down_revision: Union[str, None] = '3747e8230aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('o_url', sa.String(), nullable=True),
    sa.Column('s_url', sa.String(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
